# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8663e22716693ada7e6b1569df8b6e87168363f60f7e65369d48d7d5c363ba06764149b74249636fadd7da1041d57b0c6b77fd86ad09b10b3eb681044bc22c5

test:
  secret_key_base: dd2f308bfccc5c0b69cc0f303e817190f165835589d29dadde80d6a4c1c3cbfc00d114c8efca31261c5300243614afae66dbe9acdf5b672816b9fa68abd53b3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
